export const AboutMeObject = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'About Me',
    heading: 'Full Stack Developer',
    description: '',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_profile_pic_ic5t.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: true,
}

export const ResumeObject = {
    id: 'resume',
    lightBg: false,
    lightText: true,
    lightTextdesc: true,
    topLine: 'My Resume',
    heading: 'Current Resume',
    description: 'This is Resume',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_sync_files_xb3r.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: false,
}


export const DiscoverObject = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextdesc: true,
    topLine: 'Discover',
    heading: 'Java Developer \nSoftware Engineer',
    description: '',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_profile_pic_ic5t.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: false,
}

export const ProjectObject = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextdesc: true,
    topLine: 'My Projects',
    heading: 'Java Developer \nSoftware Engineer',
    description: 'This is Project',
    buttonLabel: 'View my resume',
    imgStart: false,
    img: '/images/undraw_data_reports_706v.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: false,
}


export const SkillObject = {
    id: 'skills',
    lightBg: true,
    lightText: false,
    lightTextdesc: true,
    topLine: 'My Skills',
    heading: 'Front End : ReactJS, HTML5, CSS3, Bootstrap, AngularJS \nBack End: SpringBoot, AWS',
    description: 'This is Project',
    buttonLabel: 'View my resume',
    imgStart: true,
    img: '/images/',
    alt:'AboutMeSvg',
    dark: false,
    primary: true,
    darkText: true,
}