export const AboutMeObject = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextdesc: false,
    topLine: 'About Me',
    heading: 'Full Stack Developer',
    description: '',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_profile_pic_ic5t.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: true,
}

export const ResumeObject = {
    id: 'resume',
    lightBg: true,
    lightText: false,
    lightTextdesc: true,
    topLine: 'My Resume',
    heading: 'Current Resume',
    description: 'This is Resume',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_Internet_on_the_go_re_vben.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: false,
}


export const DiscoverObject = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextdesc: true,
    topLine: 'Discover',
    heading: 'Java Developer \nSoftware Engineer',
    description: '',
    buttonLabel: 'Check out my projects',
    imgStart: true,
    img: '/images/undraw_profile_pic_ic5t.svg',
    alt:'AboutMeSvg',
    dark: true,
    primary: true,
    darkText: false,
}